# Generated by Django 6.0.2 on 2026-02-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_visit', 'Page Visit'), ('product_click', 'Product Click'), ('category_click', 'Category Click'), ('search', 'Search'), ('whatsapp_contact', 'WhatsApp Contact')], max_length=32)),
                ('product_id', models.CharField(blank=True, max_length=64, null=True)),
                ('category_id', models.CharField(blank=True, max_length=64, null=True)),
                ('search_term', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
                ('session_id', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
